### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by ryanfortner** [Pi-Apps-Coders/website#12]
- [x] create separate page for install instructions instead of a redirect
- [x] create separate page for support, containing links to the discord server and github
- [x] fix up the navbar of the screenshots page
